### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by JorTurFer** [pfnet-research/gcp-workload-identity-federation-webhook#6]
Hello,
Do you have plans to create a helm chart for this? I'd like to use for adding e2e test in [KEDA](https://github.com/kedacore/keda) and being honest, having a helm chart it's the easiest way to deploy this :)

**Comment by everpeace** [comment]
Thank you for the feedback. Sure, I have a plan to create a helm chart. I would appreciate it if you would review once I created a PR because I don't have much experience writing helm charts. Especially most challenging part would be flexibility of `values.yaml`.

**Comment by JorTurFer** [comment]
Sure! You are solving my problems to properly e2e test WI, the minimum thing I can do is review it and give you feedback :)

**Comment by everpeace** [comment]
@JorTurFer helm chart is now available! Please see the "installation" section in README.

https://github.com/pfnet-research/gcp-workload-identity-federation-webhook#installation

note: cert-manager is required. but, prometheus-operator is optional.

If you would face some issues, please feel free to tell us.
