### ISSUE TITLE
Helm Chart kubeVersion refuses to install on EKS

### ISSUE THREAD

**Issue by alanraison** [pfnet-research/gcp-workload-identity-federation-webhook#69]
The current version of EKS (`v1.30.1-eks-1de2ab1` at the time of writing) does not pass the semver test because EKS (incorrectly) uses a pre-release version (see https://github.com/helm/helm/issues/9371).

This is preventing the Helm chart from installing on EKS.

**Comment by ordovicia** [comment]
Thank you for the PR!
